service: vis
functions:
  summariser:
    handler: summarise
    events:
      - event:
          eventType: google.storage.object.finalize
          resource: 'projects/${self:provider.project, ""}/buckets/${self:custom.bucketName}'

plugins:
  - serverless-google-cloudfunctions
provider:
  name: google
  runtime: python37
  project: visumm
  credentials: ~/.gcloud/visumm-08ef11d690f5.json
custom:
  bucketName: visumm-store