service: vis
functions:
  get_yt_video:
    handler: get_yt_video
    events:
      - event:
          eventType: google.storage.object.finalize
          resource: 'projects/${self:provider.project, ""}/buckets/${self:custom.bucketName}'
  summariser:
    handler: summarise
    events:
      - event:
          eventType: google.storage.object.finalize
          resource: 'projects/${self:provider.project, ""}/buckets/${self:custom.bucketName}'
  extract_audio:
    handler: transform_audio
    events:
      - event:
          eventType: google.storage.object.finalize
          resource: 'projects/${self:provider.project, ""}/buckets/${self:custom.bucketName}'
  
  audio_to_text:
    handler: sample_long_running_recognize
    events:
      - event:
          eventType: google.storage.object.finalize
          resource: 'projects/${self:provider.project, ""}/buckets/${self:custom.bucketName}'

plugins:
  - serverless-google-cloudfunctions
provider:
  name: google
  runtime: python37
  project: visumm
  credentials: ~/.gcloud/visumm-08ef11d690f5.json
custom:
  bucketName: visumm-store